

CREATE TABLE keywords (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   keyword VARCHAR(255),
   priority_id INTEGER,
   type_id INTEGER,
   CONSTRAINT keywords_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255),
   last_name VARCHAR(255),
   password VARCHAR(255),
   username VARCHAR(255),
   enable BOOLEAN,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE keywords ADD CONSTRAINT uc_keywords_keyword UNIQUE (keyword);

ALTER TABLE users ADD CONSTRAINT uc_user_username UNIQUE (username);

CREATE TABLE comment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   date TIMESTAMP WITHOUT TIME ZONE,
   description VARCHAR(255),
   message_id INTEGER,
   CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   actual BOOLEAN,
   date TIMESTAMP WITHOUT TIME ZONE,
   description VARCHAR(255),
   status VARCHAR(255),
   support_id INTEGER,
   priority_id INTEGER,
   type_id INTEGER,
   user_id INTEGER,
   CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE priority (
  id INTEGER NOT NULL,
   description VARCHAR(255),
   CONSTRAINT priority_pkey PRIMARY KEY (id)
);

CREATE TABLE quick (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   CONSTRAINT quick_pkey PRIMARY KEY (id)
);

CREATE TABLE role (
  id INTEGER NOT NULL,
   role VARCHAR(255),
   CONSTRAINT role_pkey PRIMARY KEY (id)
);

CREATE TABLE type (
  id INTEGER NOT NULL,
   description VARCHAR(255),
   CONSTRAINT type_pkey PRIMARY KEY (id)
);

CREATE TABLE users_roles (
  user_id INTEGER NOT NULL,
   role_id INTEGER NOT NULL,
   CONSTRAINT users_roles_pkey PRIMARY KEY (user_id, role_id)
);



ALTER TABLE users_roles ADD CONSTRAINT fkdxdy3w4bd1qmgc4ei96as8q7m FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE messages ADD CONSTRAINT fkej8b9te3cse4b0m78nj06ynfx FOREIGN KEY (priority_id) REFERENCES priority (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE comment ADD CONSTRAINT fkg3a0yldy6lwt7c8rijeupue8q FOREIGN KEY (message_id) REFERENCES messages (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE messages ADD CONSTRAINT fkjmuqmsuy8noexy1yfi9y8by1 FOREIGN KEY (type_id) REFERENCES type (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE messages ADD CONSTRAINT fkqy7vt3eprfi1p28v1t3ah11yo FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE users_roles ADD CONSTRAINT fkt4v0rrweyk393bdgt107vdx0x FOREIGN KEY (role_id) REFERENCES role (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


INSERT INTO users (username, password, first_name, last_name, enable)
VALUES  ('admin', '$2a$12$XKO.Y95Vtm.BhLPjdH/r2ed1mYCXrq0FzuosnqJtQckA.xZXFraxe', 'Default', 'Admin', TRUE);

INSERT INTO role (id, role)
VALUES (3, 'ROLE_USER'),
       (2, 'ROLE_SUPPORT'),
       (1, 'ROLE_ADMIN');

INSERT INTO users_roles (role_id, user_id)
VALUES (1, 1);

INSERT INTO type (id, description)
VALUES (0, 'Прочее');

INSERT INTO priority (id, description)
VALUES (0, 'Срочно'),
       (1, 'Обычный'),
       (2, 'Низкий');